name: Build and deploy Python project to Azure Function App - triangulationtest

on:
  push:
    branches: [ main ]
    paths:
      - 'ConformityRatio/**'
      - '.github/workflows/main_triangulationtest.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'ConformityRatio/**'
      - '.github/workflows/main_triangulationtest.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'ConformityRatio'
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # No need to create a venv or install locally if you use remote build.
      - name: Zip artifact for deployment
        run: zip -r release.zip ./

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip -q release.zip

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_57D8C1B5F3514EB692794EE71A1447A7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8BC74F6B62F04DF9A626DF2EA1A589D6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_79B73407848D4A9DB3EA116E3A256BF6 }}

      - name: Deploy to Azure Functions (remote build)
        uses: Azure/functions-action@v1
        with:
          app-name: 'triangulationtest'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          enable-oryx-build: true
          scm-do-build-during-deployment: true
